/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as NeetPlannerRouteImport } from './routes/neet-planner'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos.index'
import { Route as ReposNewRouteImport } from './routes/repos.new'
import { Route as ReposIdRouteImport } from './routes/repos.$id'
import { Route as AppIdRouteImport } from './routes/app.$id'
import { Route as ApiAdminSetupStorageRouteImport } from './routes/api/admin/setup-storage'
import { Route as ApiPublicInstallIdRouteImport } from './routes/api/public/install.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const NeetPlannerRoute = NeetPlannerRouteImport.update({
  id: '/neet-planner',
  path: '/neet-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposNewRoute = ReposNewRouteImport.update({
  id: '/repos/new',
  path: '/repos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/repos/$id',
  path: '/repos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetupStorageRoute = ApiAdminSetupStorageRouteImport.update({
  id: '/api/admin/setup-storage',
  path: '/api/admin/setup-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstallIdRoute = ApiPublicInstallIdRouteImport.update({
  id: '/api/public/install/$id',
  path: '/api/public/install/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/neet-planner': typeof NeetPlannerRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
  '/repos/$id': typeof ReposIdRoute
  '/repos/new': typeof ReposNewRoute
  '/repos/': typeof ReposIndexRoute
  '/api/admin/setup-storage': typeof ApiAdminSetupStorageRoute
  '/api/public/install/$id': typeof ApiPublicInstallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/neet-planner': typeof NeetPlannerRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
  '/repos/$id': typeof ReposIdRoute
  '/repos/new': typeof ReposNewRoute
  '/repos': typeof ReposIndexRoute
  '/api/admin/setup-storage': typeof ApiAdminSetupStorageRoute
  '/api/public/install/$id': typeof ApiPublicInstallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/neet-planner': typeof NeetPlannerRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
  '/repos/$id': typeof ReposIdRoute
  '/repos/new': typeof ReposNewRoute
  '/repos/': typeof ReposIndexRoute
  '/api/admin/setup-storage': typeof ApiAdminSetupStorageRoute
  '/api/public/install/$id': typeof ApiPublicInstallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/neet-planner'
    | '/upload'
    | '/app/$id'
    | '/repos/$id'
    | '/repos/new'
    | '/repos/'
    | '/api/admin/setup-storage'
    | '/api/public/install/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/neet-planner'
    | '/upload'
    | '/app/$id'
    | '/repos/$id'
    | '/repos/new'
    | '/repos'
    | '/api/admin/setup-storage'
    | '/api/public/install/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/neet-planner'
    | '/upload'
    | '/app/$id'
    | '/repos/$id'
    | '/repos/new'
    | '/repos/'
    | '/api/admin/setup-storage'
    | '/api/public/install/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  NeetPlannerRoute: typeof NeetPlannerRoute
  UploadRoute: typeof UploadRoute
  AppIdRoute: typeof AppIdRoute
  ReposIdRoute: typeof ReposIdRoute
  ReposNewRoute: typeof ReposNewRoute
  ReposIndexRoute: typeof ReposIndexRoute
  ApiAdminSetupStorageRoute: typeof ApiAdminSetupStorageRoute
  ApiPublicInstallIdRoute: typeof ApiPublicInstallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neet-planner': {
      id: '/neet-planner'
      path: '/neet-planner'
      fullPath: '/neet-planner'
      preLoaderRoute: typeof NeetPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/new': {
      id: '/repos/new'
      path: '/repos/new'
      fullPath: '/repos/new'
      preLoaderRoute: typeof ReposNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/repos/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/setup-storage': {
      id: '/api/admin/setup-storage'
      path: '/api/admin/setup-storage'
      fullPath: '/api/admin/setup-storage'
      preLoaderRoute: typeof ApiAdminSetupStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/install/$id': {
      id: '/api/public/install/$id'
      path: '/api/public/install/$id'
      fullPath: '/api/public/install/$id'
      preLoaderRoute: typeof ApiPublicInstallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  NeetPlannerRoute: NeetPlannerRoute,
  UploadRoute: UploadRoute,
  AppIdRoute: AppIdRoute,
  ReposIdRoute: ReposIdRoute,
  ReposNewRoute: ReposNewRoute,
  ReposIndexRoute: ReposIndexRoute,
  ApiAdminSetupStorageRoute: ApiAdminSetupStorageRoute,
  ApiPublicInstallIdRoute: ApiPublicInstallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
